### ISSUE TITLE
Performance difference between papers and released weights

### ISSUE THREAD

**Issue by sungonce** [MCC-WH/Token#10]
Hello @MCC-WH
Thank you for sharing the good code.

I have noticed a huge performance difference between your paper and the released weight, especially on the +1M experiments.

|                                          | ROxf-M |  +1M | RPar-M |  +1M | ROxf-H |  +1M | RPar-H |  +1M |
|:----------------------------------------:|:------:|:----:|:------:|:----:|:------:|:----:|:------:|:----:|
|      TOKEN-R50-Paper | 79.42 | **73.68** | **88.67** | **77.56** | 59.48 | **49.55** | **76.49** | **58.92**
| TOKEN-R50-Released weights | **79.79** | 67.36 | 88.08 | 74.33 | **62.68** | 45.70 | 75.49 | 52.68
| TOKEN-R101-Paper | **82.28** | **75.64** | 89.34 | **79.76** | **66.57** | **51.37** | **78.56** | **61.56**
| TOKEN-R101-Released weights | 82.16 | 70.58 | **89.40** | 77.24 | 65.75 | 47.46 | 78.44 | 56.81

The same goes for the DELG you reproduced.
|                                          | ROxf-M |  +1M | RPar-M |  +1M | ROxf-H |  +1M | RPar-H |  +1M |
|:----------------------------------------:|:------:|:----:|:------:|:----:|:------:|:----:|:------:|:----:|
|      DELG-R101-Reproduced-Paper | 78.24 | **68.36** | 88.21 | **75.83** | 60.15 | **44.41** | **76.15** | **52.40**
| DELG-R101-Reproduced-Released weights | **78.55** | 66.02 | **88.58** | 73.65 | **60.89** | 41.75 | 76.05 | 51.46

Could you please check if the performance of the paper has errors?
If the performance of the paper is correct, could you please share the model (R50-Token, R101-Token) weights used in the paper to check the paper's performance?
It should also be noted that this may also affect the reviews/results of many (landmark) image retrieval papers submitted or to be submitted to the conferences/journals.

**Comment by MCC-WH** [comment]
Hi, Thanks for your interest in our work! In the [arixv version](https://arxiv.org/abs/2112.06159) of our paper, the performance does differ from the publicly available model. Since I neglect to do cropping operations for the query images. The performance of the public model should now be the real performance. We have updated the errors in the official [camera ready version](https://ojs.aaai.org/index.php/AAAI/article/view/20173) submitted to AAAI. We will update the arixv version in the near future. Please refer to the official version provided by AAAI. Thanks again for noticing the issue.

**Comment by MCC-WH** [comment]
@sungonce

**Comment by sungonce** [comment]
Hi again,
Thanks for the fast reply :D
I checked the difference between the arxiv version and the AAAI version and confirmed that the real performance was updated correctly.
Thanks again for the reply and looking forward to good research in the future.

**Comment by MCC-WH** [comment]
Thanks! I also noticed [your paper](https://openaccess.thecvf.com/content/CVPR2022/html/Lee_Correlation_Verification_for_Image_Retrieval_CVPR_2022_paper.html) at CVPR2022, a very nice and solid solution!

**Comment by upupbo** [comment]
hello,Can you provide training codes about CVNet @sungonce 
I hope you can update and provide the training code of CVNet papers. Thank you
