### ISSUE TITLE
can you public pretrain model ? thanks

### ISSUE THREAD

**Issue by phamdan** [MCC-WH/Token#3]

**Comment by MCC-WH** [comment]
This work is related to some company projects, so we can not provide the optimal mode parameters at this time.

**Comment by MCC-WH** [comment]
This work is related to some company projects, so we can not provide the optimal model parameters at this time.

**Comment by phamdan** [comment]
> This work is related to some company projects, so we can not provide the optimal model parameters at this time.

i have a question . result  map on dataset roxford = ?  if i train model according to your instruction. thanks

**Comment by MCC-WH** [comment]
Please refer to [issue About the training logger and best_checkpoint.pth](https://github.com/MCC-WH/Token/issues/2).
