### ISSUE TITLE
error test

### ISSUE THREAD

**Issue by phamdan** [MCC-WH/Token#5]

**Comment by MCC-WH** [comment]
I'm sorry about that. I will upload the test code for the comparison methods within a week.

**Comment by phamdan** [comment]
> I'm sorry about that. I will upload the test code for the comparison methods within a week.
if possible can you guide me how to run pretrain mode solar? .I tried to test solar model and got the same error as this token. thanks

**Comment by MCC-WH** [comment]
I just update the network part and the test code, you can try it now. You need to modify the model and load the corresponding model weights.
