### ISSUE TITLE
Which model is used as RetrievalNet?

### ISSUE THREAD

**Issue by milliema** [MCC-WH/Token#6]
https://github.com/MCC-WH/Token/blob/928a6ccb260a1f3f02b3dcf5b3490c3fcd7d3050/train.py#L100
RetrievalNet(args.classifier_num) does not refer to any models defined in networks.py, is this correct?

**Comment by MCC-WH** [comment]
sorry for that, I have changed the relevant code

**Comment by milliema** [comment]
@MCC-WH Hi. I still couldn't correlate the steps in the paper with your code.
As depicted in your paper Fig2, the whole process includes: LFSA, tokenizr (spatial attention), and refinement (relationship modelling, visual token enhancement);
However, the codes has only backbone and token refine parts. I guess you 've included all the steps in Token_Refine class. What are the meaning of conv, encoder, query, decoder, and what are the corresponding blocks in the paper? More details and hints are appreciated!
